services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file: ./bot/.env
    volumes:
      - .:/app
    depends_on:
      - api
    restart: unless-stopped
