services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file: ./bot/.env
    volumes:
      - .:/app
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
