services:
  api:
    image: ghcr.io/${GITHUB_OWNER}/my-api:sha-${REF}
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./api/pint_economy.json:/app/api/pint_economy.json:rw,Z  
  
  bot:
    image: ghcr.io/${GITHUB_OWNER}/my-bot:sha-${REF}
    env_file: ./bot/.env
    restart: unless-stopped
    network_mode: host
    depends_on:
      - api