services:
  api:
    image: ghcr.io/${GITHUB_OWNER}/my-api:${REF}
    env_file: ./api/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  bot:
    image: ghcr.io/${GITHUB_OWNER}/my-bot:${REF}
    env_file: ./bot/.env
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
